# Generated by Django 6.0.2 on 2026-05-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0003_projectrating_projectreview_alter_project_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectreview',
            name='image',
        ),
    ]
