# Generated by Django 6.0.2 on 2026-05-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0004_remove_projectreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectreview',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
