# Generated by Django 6.0.2 on 2026-05-04 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0005_projectreview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='diyprojects.project'),
        ),
    ]
