# Generated by Django 6.0.2 on 2026-05-04 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0008_projectrating_project_projectreview_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='diyprojects.project'),
        ),
        migrations.AddField(
            model_name='projectrating',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='diyprojects.project'),
        ),
        migrations.AddField(
            model_name='projectreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='diyprojects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='diyprojects.projectcategory'),
        ),
    ]
