# Generated by Django 6.0.2 on 2026-05-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0010_project_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='diyprojects.project'),
        ),
    ]
