# Generated by Django 6.0.3 on 2026-05-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0004_alter_commission_options_commission_maker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Full'), (2, 'Completed'), (3, 'Discontinued')], default=0),
        ),
    ]
