# Generated by Django 6.0.2 on 2026-05-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Book Contributor', 'Book Contributor'), ('Commission Maker', 'Commission Maker'), ('Project Creator', 'Project Creator'), ('Event Organizer', 'Event Organizer'), ('Market Seller', 'Market Seller')], default='Regular', max_length=50),
        ),
    ]
