# Generated by Django 6.0.1 on 2026-05-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_alter_bookmark_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
