# Generated by Django 6.0.2 on 2026-03-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_commission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='due_date',
        ),
    ]
