# Generated by Django 6.0.2 on 2026-03-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on'], 'verbose_name': 'project', 'verbose_name_plural': 'project'},
        ),
    ]
